kind: Service
apiVersion: v1
metadata:
  name: stemcstudio-search-service
spec:
  selector:
    app: stemcstudio-search
    version: "1"
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer